"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { ClerkProvider } from "@clerk/nextjs";
import RoleSelectionPopup from "@/components/RoleSelectionPopup";
import { useWallet, WalletProvider } from "@/lib/context/WalletContext";
import CompanyDetailsPopup from "@/components/CompanyDetailsPopup";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <WalletProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-primary`}
          >
            <Navbar />
            <RoleSelectionPopup />
            <CompanyDetailsPopup />
            <div className=" pt-20"></div>
            {children}
          </body>
        </html>
      </WalletProvider>
    </ClerkProvider>
  );
}
